config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :ideas

  root 'users#new'

  get 'login' => 'sessions#new', as: 'new_login'

  post 'login' => 'sessions#create', as: 'login'

  delete 'logout' => 'sessions#destroy', as: 'logout'

  post 'idea/:id/add' => 'likes#create', as: 'like'

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
  has_many :likes
  has_many :likers, through: :likes, source: :user

  validates :content, length: {minimum: 5}, presence: true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :ideas, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liking, through: :likes, source: :idea

  email_validate = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  validates :name, :alias, presence: true
  validates :email, presence: true, uniqueness: true, format: {with: email_validate}

  before_save :downcase_email
  
  def downcase_email
      self.email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  private
	def require_login
		redirect_to '/login' if current_user == nil
	end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
	before_action :require_login

	def index
		@user = User.find(current_user)
		@idea = Idea.all
		
	end

	def create
		@idea = Idea.new(idea_params)

		if @idea.save
			flash[:notice] = ["Successfully created idea"]
			return redirect_to ideas_path
		end
		flash[:errors] = @idea.errors.full_messages
		return redirect_to :back
	end

	def destroy
		@idea = Idea.find(params[:id])

		@idea.delete if @idea.user == current_user

		return redirect_to ideas_path(current_user)
	end

	def show
		@user = User.find(params[:id])
		@idea = Idea.find(params[:id])
	end

	private
		def idea_params
			params.require(:idea).permit(:content).merge(user: current_user)
		end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :require_login
	def create
		idea = Idea.find(params[:id])
		Like.create(user:current_user, idea:idea) unless idea.likers.include? current_user

		return redirect_to ideas_path
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_action :require_login, only: [:destroy]
  def new
  end

  def create
  	flash[:errors] ||= []

  	@user = User.find_by_email(params[:email])

  	@user.try(:authenticate, params[:password])
  	
  	if @user
  		if @user.try(:authenticate, params[:password])
  			
  			session[:user_id] = @user.id

  			return redirect_to ideas_path
  		end
  		
  		flash[:errors] << 'Password is incorrect.'
  	else
  		flash[:errors] << 'Account not found, please register.'
  	end

  	return redirect_to '/login'
  end

  def destroy
  	session.clear

  	flash[:notice] = ["Successfully Logged Out"]

  	return redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_login, except: [:new, :create]
	before_action :authorized, only: [:edit, :update, :destroy]

  def new
  
  end

  def create
  	@user = User.new(user_params)
  	
  	if @user.save

  		session[:user_id] = @user.id
  		
  		return redirect_to ideas_path
  	end

  	flash[:errors] = @user.errors.full_messages

  	return redirect_to :back
  end

  def show
  	@user = User.find(params[:id])

  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])

  	if @user.update(user_params)
		flash[:notice] = ["Successfully updated user"]
		return redirect_to ideas_path
 	end

 	flash[:errors] = @user.errors.full_messages
	return redirect_to :back
	end

  def destroy
  	@user = User.find(params[:id])

		@user.delete

		session.clear

		flash[:notice] = ["Deleted account"]

		return redirect_to new_user_path
  end

  private
  	def user_params
  		params.require(:user).permit(:name, :alias, :email, :password, :password_confirmation)
  	end
  	# def authorized
   #    return redirect_to ideas_path(current_user) unless current_user.id == params[:id].to_i
   #  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<style type="text/css">
		input {
			width: 300px;
		}
		.box {
			width: 250px;
			border: 1px solid black

		}
	</style>
</head>
<body>

<h3>Hi, <%= @user.alias %>!</h3>

<form action="/ideas" method="post">
		<input type="hidden" name="authenticity_token" class="<%=form_authenticity_token%>">
		<p><input type="text" name="idea[content]" placeholder="Post something witty here..."> <button type="submit">Idea!</button></p>
</form>

<% @idea.sort{ |a,b| b.likes.count <=> a.likes.count}.each do |idea| %>
	<p><a href="/users/<%= idea.user.id %>"><%= idea.user.alias %></a> says:</p>
	<div class="box">
		<%= idea.content %></p>
	</div>
	<p><%= link_to "Like", like_path(:id => idea.id), :method => :create %> 

	<a href="/ideas/<%= idea.id %>"><%= idea.likes.count %> people</a> like this</p>
	
	
	
	<% if idea.user == current_user %>
		<a href="/ideas/<%= idea.id %>" data-method="delete">Delete</a>
	<% end %>
	<hr>
<% end %>

</body>
</html>

app/views/ideas/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<style type="text/css">
		.box{
			width: 250px;
			border: 1px solid black
		}
	</style>
</head>
<body>

<a href="/ideas">Bright Ideas</a>

<p><a href="/users/<%= @user.id %>"><%= @idea.user.alias %></a> says:</p>
<div class="box">
<p><%= @idea.content %></p>
</div>
<br>
<p>People who liked this post:</p>
<table>
	<tr>
		<th>Alias</th>
		<th>Name</th>
	</tr>
	<% @idea.likers.each do |person| %>
	<tr>
		<td><a href="/users/<%= person.id %>"><%= person.alias %></a></td>
		<td><%= person.name %></td>
	</tr>
	<% end %>
</table>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BeltReviewer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<% if current_user %>
	<a href="<%= logout_path %>" data-method="delete">Logout</a>
<% end %>

<% if flash[:errors] %>
  	<% flash[:errors].each do |e| %>
    	<p class="text-danger"><%= e %></p>
  	<% end %>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<p>Returning User? <a href="/login">Login</a></p>
<h3>Register</h3>

<form action="/users" method="post">
		<input type="hidden" name="authenticity_token" class="<%=form_authenticity_token%>">
			<p>Name:<input type="text" name="user[name]"></p>

			<p>Alias: <input type="text" name="user[alias]"></p>

			<p>Email: <input type="text" name="user[email]"></p>

			<p>Password: <input type="password" name="user[password]"></p>

			<p><small>*Password should be at least 8 characters</small></p>

			<p>Password Confirmation: <input type="password" name="user[password_confirmation]"></p>

			<p><button type="submit">Register</button></p>

		</form>

app/views/users/show.html.erb
<a href="/ideas">Bright Ideas</a>

<p>Name: <%= @user.name %></p>
<p>Alias: <%= @user.alias %></p>
<p>Email: <%= @user.email %></p>

<hr>

<p>Total Number of Posts: <%= @user.ideas.count %></p>
<p>Total Number of Likes: <%= @user.likes.count %></p>